# Generated by Django 5.2.6 on 2025-10-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category_article_slug_article_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
