# Generated by Django 5.2.6 on 2025-10-16 15:14

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('article', 'Category')

    categories = [
        {'title': 'Esportes', 'slug': 'esportes'},
        {'title': 'Política', 'slug': 'politica'},
        {'title': 'Economia', 'slug': 'economia'},
        {'title': 'cultura', 'slug': 'cultura'},
        {'title': 'Tecnologia', 'slug': 'tecnologia'},
    ]

    for category in categories:
        Category.objects.get_or_create(slug=category['slug'], defaults={'title': category['title']})

def remove_categories(apps, schema_editor):
    Category = apps.get_model('article', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_image'),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories),
    ]
